import ThemeContext from '@/components/ThemeContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Raleway } from 'next/font/google'
import Header from '@/components/Header'
import ContactBtn from '@/components/ContactBtn'


const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Matthew Carby',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=' overflow-x-hidden'>
      <body className={`${inter.className} min-h-screen`}>
        <ThemeContext>
          <div className=''>
            <Header />
          </div>

          <div className='max-h-screen overflow-scroll md:px-[10%]'>
            {children}
            <span className='fixed right-[20px] bottom-[20px] lg:right-[40px] lg:bottom-[40px] xl:right-[40px] xg:bottom-[60px]'>
              <ContactBtn />
            </span>
          </div>
        </ThemeContext>
      </body>
    </html>
  )
}
